In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/DoBIH_v17_3.csv")#, index_col="Number")

/tmp/ipykernel_15054/1248020207.py:1: DtypeWarning: Columns (3,25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/DoBIH_v17_3.csv")#, index_col="Number")

In [3]:
subset = data[["Number", "Name", "Feature", "Metres", "Classification", "Latitude", "Longitude", "MT", "M", "C", "xMT", "D", "DT", "G"]]
#subset['Number'] = subset.Number

In [4]:
subset = subset.query("MT == 1|M == 1|C == 1|xMT == 1|D == 1|DT == 1|G == 1")[["Number", "Name", "Feature", "Metres", "Classification", "Latitude", "Longitude"]]

In [5]:
data = pd.read_csv("../data/DoBIH_v17_3.csv", index_col="Number")

/tmp/ipykernel_15054/4066627740.py:1: DtypeWarning: Columns (3,25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/DoBIH_v17_3.csv", index_col="Number")

In [7]:
import yaml

In [9]:
import json

In [10]:
data = pd.read_csv("../data/DoBIH_v17_3.csv", index_col="Number")
data['Number'] = data.index
subset = data.query("MT == 1|M == 1|C == 1|xMT == 1|D == 1|DT == 1|G == 1")[["Number", "Name", "Feature", "Metres", "Classification", "Latitude", "Longitude"]]
json_data = subset.to_dict(orient="records")
with open("hills.json", "w") as datafile:
    json.dump(json_data, datafile)

/tmp/ipykernel_15054/2065312460.py:1: DtypeWarning: Columns (3,25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/DoBIH_v17_3.csv", index_col="Number")

In [13]:
subset.to_csv("hills.csv")

In [8]:
with open("hills.yaml", "w") as datafile:
    yaml.safe_dump(json_data, datafile)

NameError: name 'json_data' is not defined

In [6]:
data = data[["Name", "Feature", "Metres", "Classification", "Latitude", "Longitude"]]
json_data['Number'] = data.index
json_data = data.to_dict(orient="index")

NameError: name 'json_data' is not defined

In [65]:
subset.to_dict(orient='index')

{0: {'Number': 1,
  'Name': 'Ben Chonzie',
  'Feature': 'cairn/shelter',
  'Metres': 931.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.453851,
  'Longitude': -3.992057},
 1: {'Number': 2,
  'Name': 'Creagan na Beinne',
  'Feature': 'cairn',
  'Metres': 888.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.506927,
  'Longitude': -4.041692},
 2: {'Number': 3,
  'Name': 'Creag Uchdag',
  'Feature': 'trig point',
  'Metres': 879.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.465278,
  'Longitude': -4.098107},
 3: {'Number': 4,
  'Name': 'Auchnafree Hill',
  'Feature': 'small cairn',
  'Metres': 789.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.454346,
  'Longitude': -3.934667},
 4: {'Number': 5,
  'Name': "Shee of Ardtalnaig [Ciste Buide a' Claidheimh]",
  'Feature': 'no feature',
  'Metres': 759.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.491391,
  'Longitude': -4.06498},
 5: {'Number': 6,
  'Name': 'Beinn na Gainimh',
  'Feature': 'no feature: ground 20m WNW of cairn',
  'Metres': 729.3,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.48786,
  'Longitude': -3.890049},
 6: {'Number': 7,
  'Name': 'Meall Buidhe',
  'Feature': 'rock 10m N of cairn',
  'Metres': 719.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.419022,
  'Longitude': -4.308646},
 7: {'Number': 8,
  'Name': 'Creag Ruadh',
  'Feature': 'smooth rock outcrop 15m W of cairn',
  'Metres': 712.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.436799,
  'Longitude': -4.152177},
 8: {'Number': 9,
  'Name': 'Meall Dearg',
  'Feature': 'trig point',
  'Metres': 690.2,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.552183,
  'Longitude': -3.812768},
 9: {'Number': 10,
  'Name': 'Creag Each',
  'Feature': 'small cairn on rocky prominence',
  'Metres': 673.7,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.410309,
  'Longitude': -4.185387},
 10: {'Number': 11,
  'Name': 'Creag Gharbh',
  'Feature': 'rock 1m NE of trig point',
  'Metres': 637.4,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.46677,
  'Longitude': -4.221506},
 11: {'Number': 12,
  'Name': 'Meall nan Caorach',
  'Feature': 'collapsed cairn/shelter 2m E of trig point',
  'Metres': 623.7,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.484896,
  'Longitude': -3.741233},
 12: {'Number': 13,
  'Name': 'Meall Reamhar',
  'Feature': 'cairn',
  'Metres': 617.8,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.479061,
  'Longitude': -3.751683},
 16: {'Number': 17,
  'Name': 'Ben Vorlich',
  'Feature': 'trig point',
  'Metres': 985.3,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.34268,
  'Longitude': -4.219448},
 17: {'Number': 18,
  'Name': "Stuc a' Chroin",
  'Feature': 'cairn on E side of summit',
  'Metres': 973.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.329315,
  'Longitude': -4.237533},
 18: {'Number': 19,
  'Name': 'Beinn Each',
  'Feature': 'small cairn',
  'Metres': 813.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.313957,
  'Longitude': -4.262183},
 19: {'Number': 20,
  'Name': 'Meall na Fearna',
  'Feature': 'small pile of stones',
  'Metres': 809.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.341247,
  'Longitude': -4.184316},
 21: {'Number': 22,
  'Name': "Sgiath a' Chaise",
  'Feature': 'iron fence-post in hole surrounded by a few rocks',
  'Metres': 644.2,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.323613,
  'Longitude': -4.291787},
 22: {'Number': 23,
  'Name': 'Mor Bheinn',
  'Feature': 'rock by trig point',
  'Metres': 640.3,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.36537,
  'Longitude': -4.079693},
 25: {'Number': 26,
  'Name': 'Ben More',
  'Feature': 'trig point',
  'Metres': 1174.0,
  'Classification': 'Ma,M,Sim,CoU,CoA',
  'Latitude': 56.385952,
  'Longitude': -4.540087},
 26: {'Number': 27,
  'Name': 'Stob Binnein',
  'Feature': 'cairn',
  'Metres': 1165.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.370717,
  'Longitude': -4.535753},
 27: {'Number': 28,
  'Name': 'Stob Coire an Lochain',
  'Feature': 'small cairn on rocky outcrop',
  'Metres': 1068.0,
  'Classification': 'MT,sSim',
  'Latitude': 56.364904,
  'Longitude': -4.529521},
 28: {'Number': 29,
  'Name': 'Cruach Ardrain SW Top',
  'Feature': 'rock',
  'Metres': 1044.9,
  'Classification': 'xMT',
  'Latitude': 56.355467,
  'Longitude': -4.577899},
 29: {'Number': 30,
  'Name': 'Cruach Ardrain',
  'Feature': 'cairn',
  'Metres': 1045.9,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.356429,
  'Longitude': -4.576151},
 30: {'Number': 31,
  'Name': 'An Caisteal',
  'Feature': 'cairn',
  'Metres': 995.9,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.338618,
  'Longitude': -4.62437},
 31: {'Number': 32,
  'Name': 'Ben Lomond',
  'Feature': 'rock outcrop c 4m SE of trig point',
  'Metres': 973.7,
  'Classification': 'Ma,M,Sim,CoH',
  'Latitude': 56.190293,
  'Longitude': -4.633009},
 32: {'Number': 33,
  'Name': 'Meall na Dige',
  'Feature': 'cairn',
  'Metres': 966.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.370148,
  'Longitude': -4.510273},
 33: {'Number': 34,
  'Name': 'Stob Garbh',
  'Feature': 'cairn on rock',
  'Metres': 957.7,
  'Classification': 'Hu,MT,Sim',
  'Latitude': 56.364811,
  'Longitude': -4.573721},
 34: {'Number': 35,
  'Name': 'Beinn Tulaichean',
  'Feature': 'rock by cairn',
  'Metres': 945.8,
  'Classification': 'Hu,M,Sim',
  'Latitude': 56.342216,
  'Longitude': -4.56333},
 35: {'Number': 36,
  'Name': "Beinn a' Chroin East Top",
  'Feature': 'cairn',
  'Metres': 940.1,
  'Classification': 'MT,Sim',
  'Latitude': 56.332406,
  'Longitude': -4.599286},
 36: {'Number': 37,
  'Name': "Beinn a' Chroin West Top",
  'Feature': 'rock',
  'Metres': 937.9,
  'Classification': 'xMT',
  'Latitude': 56.331737,
  'Longitude': -4.612297},
 37: {'Number': 38,
  'Name': 'Beinn Chabhair',
  'Feature': 'small cairn',
  'Metres': 932.2,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.325779,
  'Longitude': -4.641476},
 38: {'Number': 39,
  'Name': "Creag a' Bhragit",
  'Feature': 'rock',
  'Metres': 923.0,
  'Classification': 'xMT',
  'Latitude': 56.368977,
  'Longitude': -4.513515},
 39: {'Number': 40,
  'Name': 'Stob Garbh SE Top',
  'Feature': 'rock',
  'Metres': 923.5,
  'Classification': 'xMT',
  'Latitude': 56.361046,
  'Longitude': -4.570666},
 41: {'Number': 42,
  'Name': 'Ben Ledi',
  'Feature': 'trig point',
  'Metres': 879.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.258659,
  'Longitude': -4.322375},
 42: {'Number': 43,
  'Name': "Stob a' Choin",
  'Feature': 'cairn',
  'Metres': 869.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.309673,
  'Longitude': -4.560163},
 43: {'Number': 44,
  'Name': 'Meall an t-Seallaidh',
  'Feature': 'rock 3m NNE of trig point',
  'Metres': 852.7,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.380412,
  'Longitude': -4.362599},
 44: {'Number': 45,
  'Name': 'Benvane',
  'Feature': 'cairn',
  'Metres': 821.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.293295,
  'Longitude': -4.368435},
 45: {'Number': 46,
  'Name': 'Creag Mac Ranaich',
  'Feature': 'small cairn',
  'Metres': 808.6,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.399885,
  'Longitude': -4.358052},
 46: {'Number': 47,
  'Name': 'Beinn Stacach [Ceann na Baintighearna] [Stob Fear-tomhais] [Beinn Stacath]',
  'Feature': 'no feature',
  'Metres': 771.8,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.314724,
  'Longitude': -4.468098},
 47: {'Number': 48,
  'Name': "Beinn a' Choin",
  'Feature': 'cairn',
  'Metres': 768.7,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.281081,
  'Longitude': -4.659947},
 48: {'Number': 49,
  'Name': 'The Stob',
  'Feature': 'cairn on outcrop',
  'Metres': 753.6,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.37681,
  'Longitude': -4.444528},
 49: {'Number': 50,
  'Name': 'Meall Mor',
  'Feature': 'cairn',
  'Metres': 747.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.301086,
  'Longitude': -4.613679},
 50: {'Number': 51,
  'Name': 'Ben Venue',
  'Feature': 'rock 25m E of cairn',
  'Metres': 729.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.225006,
  'Longitude': -4.461986},
 51: {'Number': 52,
  'Name': 'Stob Breac',
  'Feature': 'three stones',
  'Metres': 688.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.316393,
  'Longitude': -4.512064},
 53: {'Number': 54,
  'Name': 'Creag Mhor',
  'Feature': 'rock',
  'Metres': 658.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.335473,
  'Longitude': -4.411255},
 54: {'Number': 55,
  'Name': "Cruinn a' Bheinn",
  'Feature': 'cairn',
  'Metres': 632.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.210735,
  'Longitude': -4.637088},
 64: {'Number': 65,
  'Name': 'Ben Lui [Beinn Laoigh]',
  'Feature': 'cairn',
  'Metres': 1131.4,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.397004,
  'Longitude': -4.810509},
 65: {'Number': 66,
  'Name': 'Ben Lui NW Top',
  'Feature': 'cairn',
  'Metres': 1127.0,
  'Classification': 'xMT',
  'Latitude': 56.398021,
  'Longitude': -4.812059},
 66: {'Number': 67,
  'Name': 'Ben Oss',
  'Feature': 'cairn',
  'Metres': 1029.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.389272,
  'Longitude': -4.775488},
 67: {'Number': 68,
  'Name': 'Beinn Ime',
  'Feature': 'cairn on remains of old trig point',
  'Metres': 1012.2,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.236794,
  'Longitude': -4.817125},
 68: {'Number': 69,
  'Name': 'Beinn Dubhchraig',
  'Feature': 'cairn',
  'Metres': 978.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.391295,
  'Longitude': -4.743193},
 69: {'Number': 70,
  'Name': 'Beinn Bhuidhe',
  'Feature': 'trig point base by cairn',
  'Metres': 948.5,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.326686,
  'Longitude': -4.906709},
 70: {'Number': 71,
  'Name': 'Ben Vorlich',
  'Feature': 'cairn on rocky outcrop',
  'Metres': 943.0,
  'Classification': 'Ma,M,Sim,CoH',
  'Latitude': 56.274021,
  'Longitude': -4.755046},
 72: {'Number': 73,
  'Name': 'Ben Vorlich North Top',
  'Feature': 'cairn',
  'Metres': 931.0,
  'Classification': 'MT,sSim',
  'Latitude': 56.278801,
  'Longitude': -4.755923},
 73: {'Number': 74,
  'Name': 'Beinn Narnain',
  'Feature': 'rock outcrop by trig point',
  'Metres': 927.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.220956,
  'Longitude': -4.789003},
 74: {'Number': 75,
  'Name': "Beinn a' Chleibh",
  'Feature': 'rock by middle one of three cairns',
  'Metres': 916.3,
  'Classification': 'Hu,M,Sim,sMa',
  'Latitude': 56.39023,
  'Longitude': -4.83563},
 75: {'Number': 76,
  'Name': 'Ben Vane',
  'Feature': 'rock outcrop near small cairn',
  'Metres': 915.76,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.249786,
  'Longitude': -4.781655},
 78: {'Number': 79,
  'Name': 'The Cobbler [Ben Arthur]',
  'Feature': 'rock pinnacle',
  'Metres': 884.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.213037,
  'Longitude': -4.808042},
 79: {'Number': 80,
  'Name': 'Beinn Chuirn',
  'Feature': 'cairn',
  'Metres': 880.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.423887,
  'Longitude': -4.789867},
 80: {'Number': 81,
  'Name': 'Beinn Luibhean',
  'Feature': 'outcrop',
  'Metres': 859.7,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.23124,
  'Longitude': -4.83634},
 81: {'Number': 82,
  'Name': 'Stob Coire Creagach [Binnein an Fhidhleir]',
  'Feature': 'rock by cairn',
  'Metres': 817.8,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.257699,
  'Longitude': -4.858},
 82: {'Number': 83,
  'Name': 'Meall an Fhudair',
  'Feature': 'no feature: 3m N of cairn/shelter',
  'Metres': 764.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.33389,
  'Longitude': -4.798859},
 83: {'Number': 84,
  'Name': 'Meall nan Gabhar',
  'Feature': 'rock in centre of grassy summit',
  'Metres': 744.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.37553,
  'Longitude': -4.858479},
 85: {'Number': 86,
  'Name': 'Beinn Damhain',
  'Feature': 'rock 3m SW of cairn',
  'Metres': 684.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.316818,
  'Longitude': -4.779041},
 86: {'Number': 87,
  'Name': 'Meall Odhar',
  'Feature': 'outcrop 4m NNW of cairn',
  'Metres': 656.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.430054,
  'Longitude': -4.76172},
 87: {'Number': 88,
  'Name': 'Fiarach',
  'Feature': 'small cairn on rock',
  'Metres': 652.2,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.398535,
  'Longitude': -4.683437},
 88: {'Number': 89,
  'Name': 'Beinn Bhalgairean',
  'Feature': 'quartz stone 7m S of cairn',
  'Metres': 636.8,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.374991,
  'Longitude': -4.912105},
 92: {'Number': 93,
  'Name': 'Doune Hill',
  'Feature': 'small cairn 45m SSW of trig point',
  'Metres': 734.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.135852,
  'Longitude': -4.752523},
 93: {'Number': 94,
  'Name': 'Beinn Chaorach',
  'Feature': 'ground 2m WSW of trig point just W of fence',
  'Metres': 713.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.093329,
  'Longitude': -4.75444},
 94: {'Number': 95,
  'Name': "Beinn a' Mhanaich",
  'Feature': 'cairn',
  'Metres': 709.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.112762,
  'Longitude': -4.785269},
 95: {'Number': 96,
  'Name': 'Beinn Eich',
  'Feature': 'small cairn',
  'Metres': 703.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.114637,
  'Longitude': -4.732345},
 96: {'Number': 97,
  'Name': 'Cruach an t-Sidhein',
  'Feature': 'small cairn',
  'Metres': 684.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.12978,
  'Longitude': -4.776779},
 97: {'Number': 98,
  'Name': 'Beinn Bhreac',
  'Feature': 'rock within 1m of trig point',
  'Metres': 680.8,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.163643,
  'Longitude': -4.704559},
 98: {'Number': 99,
  'Name': 'Mid Hill [Beinn Dubh]',
  'Feature': 'cairn',
  'Metres': 657.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.129482,
  'Longitude': -4.70232},
 99: {'Number': 100,
  'Name': 'Tullich Hill',
  'Feature': 'rock 4m N of cairn',
  'Metres': 632.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.167845,
  'Longitude': -4.749948},
 102: {'Number': 103,
  'Name': 'Schiehallion',
  'Feature': 'rock 20m NW of cairn',
  'Metres': 1083.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.666933,
  'Longitude': -4.100229},
 103: {'Number': 104,
  'Name': "Beinn a' Chreachain",
  'Feature': 'large cairn',
  'Metres': 1080.6,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.560387,
  'Longitude': -4.647589},
 104: {'Number': 105,
  'Name': 'Beinn Dorain',
  'Feature': 'large cairn',
  'Metres': 1076.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.50287,
  'Longitude': -4.722157},
 106: {'Number': 107,
  'Name': 'Carn Mairg',
  'Feature': 'large cairn',
  'Metres': 1042.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.634635,
  'Longitude': -4.145608},
 107: {'Number': 108,
  'Name': 'Beinn Achaladair',
  'Feature': 'small cairn on rock outcrop',
  'Metres': 1038.6,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.551909,
  'Longitude': -4.694515},
 108: {'Number': 109,
  'Name': 'Carn Gorm',
  'Feature': 'outcrop a few metres E of cairn',
  'Metres': 1029.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.622537,
  'Longitude': -4.226021},
 109: {'Number': 110,
  'Name': 'Meall Liath',
  'Feature': 'small cairn in flat area',
  'Metres': 1012.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.634501,
  'Longitude': -4.132458},
 110: {'Number': 111,
  'Name': "Meall a' Bharr",
  'Feature': 'outcrop 2m W of small cairn',
  'Metres': 1004.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.636875,
  'Longitude': -4.172887},
 111: {'Number': 112,
  'Name': 'Beinn an Dothaidh',
  'Feature': 'cairn',
  'Metres': 1004.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.53013,
  'Longitude': -4.713981},
 112: {'Number': 113,
  'Name': 'Beinn Achaladair South Top',
  'Feature': 'slab of rock 2m SE of cairn',
  'Metres': 1003.6,
  'Classification': 'MT,Sim',
  'Latitude': 56.541126,
  'Longitude': -4.697702},
 114: {'Number': 115,
  'Name': 'Meall na Aighean',
  'Feature': 'rock 2m N of cairn',
  'Metres': 981.0,
  'Classification': 'Hu,M,Sim',
  'Latitude': 56.620627,
  'Longitude': -4.128741},
 115: {'Number': 116,
  'Name': 'Meall Buidhe',
  'Feature': 'cairn',
  'Metres': 977.2,
  'Classification': 'MT,Sim',
  'Latitude': 56.557806,
  'Longitude': -4.670341},
 117: {'Number': 118,
  'Name': 'Meall Garbh',
  'Feature': 'boulder 18m SE of large cairn',
  'Metres': 968.0,
  'Classification': 'Hu,M,Sim',
  'Latitude': 56.637381,
  'Longitude': -4.207472},
 118: {'Number': 119,
  'Name': 'Meall Garbh East Top',
  'Feature': 'embedded rock',
  'Metres': 963.7,
  'Classification': 'xMT',
  'Latitude': 56.636046,
  'Longitude': -4.202176},
 119: {'Number': 120,
  'Name': 'Stuc an Lochain [Stuchd an Lochain]',
  'Feature': 'embedded rock 3m S of cairn',
  'Metres': 960.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.570907,
  'Longitude': -4.470602},
 120: {'Number': 121,
  'Name': "Beinn a' Chreachain North Top",
  'Feature': 'rock 8m ESE of cairn',
  'Metres': 959.9,
  'Classification': 'sSim,xMT',
  'Latitude': 56.56807,
  'Longitude': -4.641321},
 121: {'Number': 122,
  'Name': 'Beinn Mhanach',
  'Feature': 'cairn',
  'Metres': 953.0,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.534041,
  'Longitude': -4.646042},
 122: {'Number': 123,
  'Name': 'Meall Buidhe',
  'Feature': 'cairn',
  'Metres': 932.1,
  'Classification': 'Ma,M,Sim',
  'Latitude': 56.617231,
  'Longitude': -4.448608},
 123: {'Number': 124,
  'Name': 'Sron Chona Choirein',
  'Feature': 'cairn',
  'Metres': 927.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.568699,
  'Longitude': -4.453658},
 124: {'Number': 125,
  'Name': 'An Sgorr',
  'Feature': 'rock 2m SE of cairn',
  'Metres': 924.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.630644,
  'Longitude': -4.217416},
 125: {'Number': 126,
  'Name': "Beinn a' Chuirn",
  'Feature': 'cairn',
  'Metres': 923.0,
  'Classification': 'MT,Sim',
  'Latitude': 56.531617,
  'Longitude': -4.668172},
 126: {'Number': 127,
  'Name': 'Meall Luaidhe',
  'Feature': 'boulder',
  'Metres': 921.1,
  'Classification': 'xMT',
  'Latitude': 56.631429,
  'Longitude': -4.191847},
 127: {'Number': 128,
  'Name': 'Meall Buidhe SE Top',
  'Feature': 'knoll on edge of corrie',
  'Metres': 917.0,
  'Classification': 'xMT',
  'Latitude': 56.608283,
  'Longitude': -4.444362},
 129: {'Number': 130,
  'Name': 'Meall Buidhe',
  'Feature': 'cairn',
  'Metres': 908.2,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.570153,
  'Longitude': -4.562},
 131: {'Number': 132,
  'Name': 'Cam Chreag',
  'Feature': 'cairn',
  'Metres': 862.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.611086,
  'Longitude': -4.385627},
 132: {'Number': 133,
  'Name': "Sron a' Choire Chnapanaich [Sron a' Choire Chnapanich]",
  'Feature': 'cairn',
  'Metres': 835.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.574181,
  'Longitude': -4.514859},
 133: {'Number': 134,
  'Name': 'Beinn Dearg',
  'Feature': 'rock 35m NNW of southern cairn',
  'Metres': 830.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.61893,
  'Longitude': -4.268971},
 134: {'Number': 135,
  'Name': 'Meall Tairneachan',
  'Feature': 'trig point',
  'Metres': 787.0,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.665904,
  'Longitude': -3.947406},
 135: {'Number': 136,
  'Name': 'Farragon Hill',
  'Feature': 'rock by cairn',
  'Metres': 782.4,
  'Classification': 'Ma,C,Sim',
  'Latitude': 56.675063,
  'Longitude': -3.894208},
 136: {'Number': 137,
  'Name': "Meall a' Mhuic",
  'Feature': 'ground 3m SW of cairn',
  'Metres': 745.0,
  'Classification': 'Ma,G,Sim',
  'Latitude': 56.627431,
  'Longitude': -4.317252},
 140: {'Number': 141,
  'Name': 'Ben Lawers',
  'Feature': 'trig point',
  'Metres': 1214.0,
  'Classification': 'Ma,M,Sim,CoH,CoU,CoA',
  'Latitude': 56.544922,
  'Longitude': -4.22086},
 141: {'Number': 142,
  'Name': 'An Stuc',
  'Feature': 'large rock 25m NE of cairn',
  'Metres': 1117.1,
  'Classification': 'Hu,M,Sim',
  'Latitude': 56.560075,

In [56]:
subset.query("Name=='The Slacks'")

Empty DataFrame
Columns: [Name, Feature, Metres, Classification, Latitude, Longitude]
Index: []

In [57]:
subset.query("""Name=="Earl's Seat" """)

Empty DataFrame
Columns: [Name, Feature, Metres, Classification, Latitude, Longitude]
Index: []